'use strict';
function sha256Fallback(text){
  const bytes=new TextEncoder().encode(text),K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0b5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const size=Math.ceil((bytes.length+9)/64)*64,msg=new Uint8Array(size);msg.set(bytes);msg[bytes.length]=0x80;const dv=new DataView(msg.buffer),bits=bytes.length*8;dv.setUint32(size-8,Math.floor(bits/0x100000000),false);dv.setUint32(size-4,bits>>>0,false);
  const H=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]),w=new Uint32Array(64),rotr=(x,n)=>(x>>>n)|(x<<(32-n));
  for(let o=0;o<size;o+=64){for(let i=0;i<16;i++)w[i]=dv.getUint32(o+i*4,false);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3),s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=H;for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^(~e&g),t1=(h+S1+ch+K[i]+w[i])>>>0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}H[0]=(H[0]+a)>>>0;H[1]=(H[1]+b)>>>0;H[2]=(H[2]+c)>>>0;H[3]=(H[3]+d)>>>0;H[4]=(H[4]+e)>>>0;H[5]=(H[5]+f)>>>0;H[6]=(H[6]+g)>>>0;H[7]=(H[7]+h)>>>0}
  return[...H].map(x=>x.toString(16).padStart(8,'0')).join('');
}
async function digestText(text,algorithm='SHA-256'){
  if(algorithm==='FNV1A32')return{algorithm:'FNV1A32',digest:(fnv1a32Text(text)>>>0).toString(16).padStart(8,'0')};
  try{if(globalThis.crypto?.subtle){const bytes=new TextEncoder().encode(text),buf=await crypto.subtle.digest('SHA-256',bytes);return{algorithm:'SHA-256',digest:[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}}}catch(_){}
  return{algorithm:'SHA-256',digest:sha256Fallback(text)};
}
function backupUnsignedPayload(payload){return payload.productVersion!==undefined&&payload.productVersion!==null?{format:payload.format,version:payload.version,productVersion:payload.productVersion,exportedAt:payload.exportedAt,project:payload.project,images:payload.images}:{format:payload.format,version:payload.version,exportedAt:payload.exportedAt,project:payload.project,images:payload.images}}
async function verifyPayloadIntegrity(payload){if(!payload?.integrity)return{ok:true,legacy:true,algorithm:null};const actual=await digestText(JSON.stringify(backupUnsignedPayload(payload)),payload.integrity.algorithm);return{ok:actual.algorithm===payload.integrity.algorithm&&actual.digest===payload.integrity.digest,legacy:false,algorithm:actual.algorithm}}
function emergencyKey(id){return `${EMERGENCY_PREFIX}${id}`}
function writeEmergencySnapshot(snapshot){try{localStorage.setItem(emergencyKey(snapshot.id),JSON.stringify({savedAt:nowISO(),checksum:projectChecksum(snapshot),project:snapshot}))}catch(_){}}
function readEmergencySnapshot(id){try{const raw=localStorage.getItem(emergencyKey(id));if(!raw)return null;const r=JSON.parse(raw);if(r.checksum!==projectChecksum(r.project))return null;return r}catch(_){return null}}
async function writeRecoverySnapshot(snapshot){const checksum=projectChecksum(snapshot),old=await dbGet(STORE_RECOVERY,snapshot.id).catch(()=>null);const same=old?.current?.checksum===checksum;const record={id:snapshot.id,current:{savedAt:nowISO(),checksum,project:clone(snapshot)},previous:same?old?.previous:(old?.current||old?.previous||null)};await dbPut(STORE_RECOVERY,record);writeEmergencySnapshot(snapshot);return record}
async function bestRecoverySnapshot(id){const r=await dbGet(STORE_RECOVERY,id).catch(()=>null),candidates=[r?.current,r?.previous,readEmergencySnapshot(id)].filter(Boolean);for(const item of candidates){const p=item.project;if(item.checksum===projectChecksum(p)&&!structuralProjectErrors(p).length)return clone(p)}return null}
function backupChecksum(payload){let h=0x811c9dc5,total=0;const add=t=>{t=String(t);total+=t.length;h=fnv1a32Text(t,h)};add(payload.format);add(payload.version);add(JSON.stringify(payload.project));for(const im of payload.images||[]){const c={...im};delete c.dataURL;add(JSON.stringify(c));add(im.dataURL||'')}return `FNV1A32-${(h>>>0).toString(16).padStart(8,'0')}-${total}`}
function readDeviceDiagnosticLocal(){try{return JSON.parse(localStorage.getItem(DEVICE_DIAG_LOCAL_KEY)||'null')}catch(_){return null}}
function writeDeviceDiagnosticLocal(v){try{localStorage.setItem(DEVICE_DIAG_LOCAL_KEY,JSON.stringify(v));return true}catch(_){return false}}
function unstableOrigin(){return location.protocol==='file:'||location.origin==='null'||location.protocol==='about:'}
async function testStorageRoundTrip(){if(!db)return{ok:false,message:'端末保存を開けません'};const id=uid('__readiness__');try{await dbPut(STORE_RECOVERY,{id,createdAt:nowISO(),test:true});const read=await dbGet(STORE_RECOVERY,id);await dbDelete(STORE_RECOVERY,id);return{ok:!!read?.test,message:read?.test?'保存・読込み正常':'保存結果を確認できません'}}catch(err){return{ok:false,message:err?.message||'保存テスト失敗'}}}
function testEmergencyStorage(){const key='__paint_quantity_readiness__';try{localStorage.setItem(key,'ok');const ok=localStorage.getItem(key)==='ok';localStorage.removeItem(key);return{ok,message:ok?'緊急保存正常':'緊急保存を確認できません'}}catch(err){return{ok:false,message:'緊急保存を利用できません'}}}
function readinessClass(check){return check.ok?'ok':check.blocking?'ng':'warn'}
function renderReadiness(result){runtimeReadiness=result;if(!els.readinessBadge)return;els.readinessBadge.className='readinessBadge '+(result.blocked?'ng':result.warnings.length?'warn':'ok');els.readinessBadge.textContent=result.blocked?'利用停止':result.warnings.length?'条件付き利用':'利用可能';els.readinessSummary.innerHTML=result.blocked?'<b style="color:#fecdd3">開始できません</b><br>'+escapeHtml(result.errors.join('／')):result.warnings.length?'<b style="color:#fde68a">条件付きで利用できます</b><br>'+escapeHtml(result.warnings.join('／')):'<b style="color:#a7f3d0">この端末で利用できます</b><br>保存・描画・整合性検査を確認しました。';els.readinessItems.innerHTML=result.checks.map(c=>`<div class="readinessItem ${readinessClass(c)}"><i class="readinessDot"></i><div><b>${escapeHtml(c.name)}</b><br>${escapeHtml(c.message)}</div></div>`).join('');els.readinessAdvice.textContent=result.blocked?'写真を選ばず、Safariの通常タブで開き直すか保存設定を確認してください。':result.warnings.length?'作業後は必ず案件バックアップを保存してください。':'作業後の案件バックアップを推奨します。'}
async function runReadinessCheck(showMessage=true){const storage=await testStorageRoundTrip(),emergency=testEmergencyStorage(),canvasOk=!!document.createElement('canvas').getContext('2d'),cryptoOk=!!globalThis.crypto?.subtle,diag=readDeviceDiagnosticLocal();let quotaMessage='容量取得非対応',quotaOk=true;try{if(navigator.storage?.estimate){const q=await navigator.storage.estimate();quotaMessage=`空き目安 ${bytesLabel(Math.max(0,(q.quota||0)-(q.usage||0)))}`;quotaOk=!q.quota||(q.quota-q.usage)>20*1024*1024}}catch(_){}const checks=[{name:'端末保存',ok:storage.ok,blocking:!storage.ok,message:storage.message},{name:'緊急復元',ok:emergency.ok,blocking:false,message:emergency.message},{name:'画像描画',ok:canvasOk,blocking:!canvasOk,message:canvasOk?'描画機能正常':'描画機能を利用できません'},{name:'整合性検査',ok:cryptoOk,blocking:false,message:cryptoOk?'標準SHA-256利用':'内蔵検査へ切替'},{name:'起動方式',ok:!unstableOrigin(),blocking:false,message:unstableOrigin()?'ローカル起動・保存注意':'HTTPS起動・安定'},{name:'保存容量',ok:quotaOk,blocking:!quotaOk,message:quotaMessage},{name:'再起動確認',ok:!!diag?.stage2PassedAt,blocking:false,message:diag?.stage2PassedAt?'確認済み':'未確認'}];const errors=checks.filter(c=>c.blocking&&!c.ok).map(c=>`${c.name}：${c.message}`),warnings=checks.filter(c=>!c.blocking&&!c.ok).map(c=>`${c.name}：${c.message}`);const result={checkedAt:nowISO(),checks,errors,warnings,blocked:errors.length>0};renderReadiness(result);if(showMessage)showToast(result.blocked?'使用前チェック：利用停止':warnings.length?'使用前チェック：条件付き利用':'使用前チェック：利用可能');return result}
function renderDeviceDiagnosticInfo(state=readDeviceDiagnosticLocal()){if(!els.deviceDiagnosticInfo)return;const originText=unstableOrigin()?'起動方式：ローカル／保存不安定の可能性':'起動方式：HTTPS／安定';if(state?.stage2PassedAt){els.deviceDiagnosticInfo.innerHTML=`<b style="color:#a7f3d0">端末診断 合格</b><br>Safari再起動後の復元を確認：${new Date(state.stage2PassedAt).toLocaleString('ja-JP')}<br>${originText}`;return}if(state?.stage1At){els.deviceDiagnosticInfo.innerHTML=`<b style="color:#fde68a">第1段階 合格</b><br>Safariを完全に閉じ、同じHTMLを開いて再度「端末診断」を押してください。<br>${originText}`;return}els.deviceDiagnosticInfo.innerHTML=`端末診断は未実施です。<br>${originText}`}
async function runDeviceDiagnostic(){try{const local=readDeviceDiagnosticLocal(),stored=await dbGet(STORE_RECOVERY,DEVICE_DIAG_ID).catch(()=>null);if(local?.token&&stored?.token===local.token&&stored.sessionId!==RUN_SESSION_ID){const state={...local,stage2PassedAt:nowISO(),stage2SessionId:RUN_SESSION_ID,origin:location.origin||location.protocol};await dbPut(STORE_RECOVERY,{...stored,stage2PassedAt:state.stage2PassedAt,stage2SessionId:RUN_SESSION_ID});writeDeviceDiagnosticLocal(state);renderDeviceDiagnosticInfo(state);showToast('端末診断合格：再起動後も保存されています');return state}if(local?.token&&stored?.token===local.token&&stored.sessionId===RUN_SESSION_ID){renderDeviceDiagnosticInfo(local);showToast('Safariを閉じて再度開いた後に実行してください');return local}const token=uid('diag'),state={token,stage1At:nowISO(),stage1SessionId:RUN_SESSION_ID,origin:location.origin||location.protocol};await dbPut(STORE_RECOVERY,{id:DEVICE_DIAG_ID,token,sessionId:RUN_SESSION_ID,stage1At:state.stage1At});if(!writeDeviceDiagnosticLocal(state))throw new Error('ブラウザの保存領域を利用できません');const check=await dbGet(STORE_RECOVERY,DEVICE_DIAG_ID);if(check?.token!==token)throw new Error('IndexedDBの再読込みに失敗しました');renderDeviceDiagnosticInfo(state);showToast('第1段階合格：Safariを閉じて再度実行してください');return state}catch(err){renderDeviceDiagnosticInfo(null);showToast(`端末診断失敗：${err.message||err}`);return null}}
async function requestPersistentStorage(){try{if(navigator.storage?.persist)await navigator.storage.persist()}catch(_){}}
async function storageStatusText(){try{if(!navigator.storage?.estimate)return 'このブラウザでは保存容量を取得できません。';const {usage=0,quota=0}=await navigator.storage.estimate();const persistent=navigator.storage.persisted?await navigator.storage.persisted():false;const ratio=quota?Math.min(100,usage/quota*100):0;return {text:`使用中 ${bytesLabel(usage)} ／ 上限目安 ${bytesLabel(quota)}\n保持設定：${persistent?'有効':'ブラウザ判断'}`,ratio}}catch(_){return '保存容量の取得に失敗しました。'}}
async function updateStorageInfo(showMessage=true){const s=await storageStatusText();const text=typeof s==='string'?s:s.text;if(els.storageInfo){els.storageInfo.innerHTML=`${escapeHtml(text).replace(/\n/g,'<br>')}<div class="storageBar"><i style="width:${typeof s==='string'?0:s.ratio}%"></i></div>`}if(showMessage)showToast(text.split('\n')[0])}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function dataURLToBlob(dataURL){const [meta,data]=String(dataURL).split(',');if(!meta||!data)throw new Error('画像データ形式が不正です');const mime=(meta.match(/data:([^;]+)/)||[])[1]||'application/octet-stream';const binary=atob(data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime})}
function loadImageFromBlob(blob){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('画像を読み込めません'))};img.src=url})}
async function compressImageFile(file){const img=await loadImageFromBlob(file);const maxEdge=2200,largest=Math.max(img.naturalWidth,img.naturalHeight);const ratio=Math.min(1,maxEdge/largest);const width=Math.max(1,Math.round(img.naturalWidth*ratio));const height=Math.max(1,Math.round(img.naturalHeight*ratio));if(file.type==='image/png'&&ratio===1&&file.size<=2*1024*1024){return {blob:file,type:file.type||'image/png',width,height,originalSize:file.size,storedSize:file.size,compressed:false}}const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob)throw new Error('画像圧縮に失敗しました');const useOriginal=ratio===1&&file.size<3*1024*1024&&blob.size>=file.size;return {blob:useOriginal?file:blob,type:useOriginal?(file.type||'image/jpeg'):'image/jpeg',width,height,originalSize:file.size,storedSize:useOriginal?file.size:blob.size,compressed:!useOriginal}}
