function syncSiteToUi(){const s=currentSite();$("siteName").value=s.name||"";$("siteDate").value=s.date||"";$("siteStaff").value=s.staff||"";$("siteAddress").value=s.address||"";$("siteMemo").value=s.memo||""}
function renderSiteSwitcher(){const s=currentSite();$("siteSwitcher").innerHTML=state.sites.map((x,i)=>`<option value="${x.id}" ${x.id===s.id?"selected":""}>${esc(x.name||"名称未入力 "+(i+1))}</option>`).join("")}
function renderItems(){const s=currentSite();$("itemList").innerHTML=s.items.map((i,n)=>`<div class="itemRow" data-id="${i.id}"><input data-k="name" value="${esc(i.name)}" placeholder="項目名"><select data-k="unit"><option ${i.unit==="㎡"?"selected":""}>㎡</option><option ${i.unit==="m"?"selected":""}>m</option><option ${i.unit==="箇所"?"selected":""}>箇所</option><option ${i.unit==="枚"?"selected":""}>枚</option><option ${i.unit==="式"?"selected":""}>式</option></select><button data-del="${i.id}" aria-label="削除">×</button></div>`).join("")||`<p class="hint">項目がありません。「＋追加」で登録してください。</p>`}
function addItem(){currentSite().items.push(blankItem("","㎡",""));renderItems();saveSoon()}
function deleteItem(id){const s=currentSite();if(s.entries.some(e=>e.itemId===id))return alert("実測履歴がある項目は削除できません。");s.items=s.items.filter(i=>i.id!==id);for(const sf of s.surfaces)sf.selectedItemIds=sf.selectedItemIds.filter(x=>x!==id);renderItems();saveSoon()}

function go(view){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));document.querySelectorAll(".bottomNav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(view==="measure")renderMeasureHome();if(view==="result")renderResults();if(view==="save")updateStorage();window.scrollTo({top:0,behavior:"smooth"})}

function renderMeasureHome(){const s=currentSite(),unfinished=[...s.surfaces].reverse().find(x=>!x.completed);$("resumeSurfaceButton").classList.toggle("hidden",!unfinished);$("resumeSurfaceButton").onclick=()=>openSurface(unfinished.id);const cards=[...s.surfaces].sort((a,b)=>b.seq-a.seq).map(sf=>`<div class="surfaceHistoryCard"><div style="display:flex;gap:9px;align-items:center">${sf.photoRef?`<img data-photo="${sf.photoRef}" alt="面${sf.seq}">`:""}<div><b>面 ${sf.seq}</b><div class="hint">${surfaceEntries(sf.id).length}件・較正${sf.calibrations.length}本・${sf.completed?(sf.completionWarnings?.length?"完了・注意":"完了"):"未完了"}</div></div></div><button data-open-surface="${sf.id}" class="small">開く</button></div>`).join("");$("surfaceHistory").innerHTML=cards||"";for(const im of $("surfaceHistory").querySelectorAll("img[data-photo]"))photoGet(im.dataset.photo).then(src=>im.src=src);$("surfaceHistory").querySelectorAll("[data-open-surface]").forEach(b=>b.onclick=()=>openSurface(b.dataset.openSurface));$("surfaceEmpty").classList.remove("hidden");$("surfaceWork").classList.add("hidden")}
function startSurface(){const s=currentSite(),sf=newSurface(s);const validItems=s.items.filter(i=>i.name.trim());sf.selectedItemIds=(s.lastSurfaceItemIds||[]).filter(id=>validItems.some(i=>i.id===id));s.surfaces.push(sf);recordAudit("surface.start",{surfaceId:sf.id,seq:sf.seq});activeSurfaceId=sf.id;openingMode=false;openingParentItemId="";openSurface(sf.id);saveSoon()}
function openSurface(id){activeSurfaceId=id;const sf=activeSurface();if(!sf)return;activeItemId=sf.selectedItemIds.find(x=>currentSite().items.some(i=>i.id===x))||"";openingMode=false;openingParentItemId="";draft=null;beamParts=[];undoStack=[];showSaved=false;$("surfaceEmpty").classList.add("hidden");$("surfaceWork").classList.remove("hidden");$("surfaceLabel").textContent=`面 ${sf.seq}`;renderSurfaceSetup();renderSurfaceStatus();}
function renderSurfaceStatus(){const sf=activeSurface();if(!sf)return;const e=$("surfaceStatus");e.textContent=sf.completed?(sf.completionWarnings?.length?"完了・注意":"完了"):sf.photoRef?`実測中 ${surfaceEntries(sf.id).length}件`:"準備中";e.className="pill "+(sf.completed&&!sf.completionWarnings?.length?"ok":sf.photoRef?"warn":"")}
function renderSurfaceSetup(){const sf=activeSurface(),s=currentSite();if(!sf)return;const items=s.items.filter(i=>i.name.trim());$("surfaceItemPicker").innerHTML=items.map(i=>`<button class="chip ${sf.selectedItemIds.includes(i.id)?"selected":""}" data-pick="${i.id}">${esc(i.name)} <small>${esc(i.unit)}</small></button>`).join("");$("surfaceItemPicker").querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{const id=b.dataset.pick;if(sf.selectedItemIds.includes(id))sf.selectedItemIds=sf.selectedItemIds.filter(x=>x!==id);else sf.selectedItemIds.push(id);b.classList.toggle("selected");touchSurface();saveSoon()});
  const haveItems=sf.selectedItemIds.length>0,havePhoto=!!sf.photoRef,haveCal=sf.calibrations.length>0||sf.calibrationSkipped;
  $("setupPanel").classList.toggle("hidden",haveItems&&havePhoto&&haveCal);
  $("stepItems").classList.toggle("hidden",haveItems&&havePhoto);
  $("stepPhoto").classList.toggle("hidden",!haveItems||havePhoto);
  $("stepCalibration").classList.toggle("hidden",!havePhoto||haveCal);
  if(haveItems&&havePhoto&&haveCal)openEditor();
}
function confirmSurfaceItems(){const sf=activeSurface();if(!sf.selectedItemIds.length)return alert("この面で測る項目を1件以上選択してください。");currentSite().lastSurfaceItemIds=[...sf.selectedItemIds];recordAudit("surface.items.confirm",{surfaceId:sf.id,count:sf.selectedItemIds.length});$("stepItems").classList.add("hidden");$("stepPhoto").classList.remove("hidden");saveSoon()}
async function setBasePhoto(file){const sf=activeSurface();if(!sf||!file)return;if(sf.photoRef&&surfaceEntries(sf.id).length&&!confirm("基準写真を変更すると、登録済みの点・線は位置根拠を失います。数量は残し、図形を未確定へ戻して写真を変更しますか？"))return;const data=await compress(file),ref=await photoPut(data);if(sf.photoRef)sf.photoHistory.push({photoRef:sf.photoRef,replacedAt:now()});sf.photoRef=ref;sf.calibrations=[];sf.calibrationRevision=0;sf.calibrationSkipped=false;sf.imageAspect=0;touchSurface();for(const e of surfaceEntries(sf.id))e.annotation=null;for(const o of sf.objects||[])o.annotation=null;recordAudit("surface.photo.set",{surfaceId:sf.id,photoRef:ref});await saveNow();$("stepPhoto").classList.add("hidden");$("stepCalibration").classList.remove("hidden");await loadStagePhoto();renderSurfaceStatus()}
async function loadStagePhoto(){const sf=activeSurface();if(!sf?.photoRef)return;const src=await photoGet(sf.photoRef),im=$("basePhoto");im.onload=()=>{const ratio=im.naturalHeight/im.naturalWidth;$("photoStage").style.aspectRatio=`${im.naturalWidth}/${im.naturalHeight}`;const svg=$("annotationSvg");svg.setAttribute("viewBox",`0 0 1000 ${1000*ratio}`);renderAnnotations()};im.src=src}
function startCalibration(){const v=Number($("calibrationValue").value);if(!(v>0))return alert("較正する実寸を入力してください。");draft={kind:"calibration",shape:"line",points:[],value:v};$("drawGuide").textContent=`較正 ${v}m：1点目→2点目`;$("setupPanel").classList.add("hidden");$("editorPanel").classList.remove("hidden");loadStagePhoto();renderAnnotations()}
function skipCalibration(){const sf=activeSurface();sf.calibrationSkipped=true;touchSurface();recordAudit("surface.calibration.skip",{surfaceId:sf.id});saveSoon();openEditor()}
function addCalibrationFromEditor(){const v=prompt("追加する較正の実寸（m）");if(v===null)return;const n=Number(v);if(!(n>0))return alert("0より大きい数値を入力してください。");draft={kind:"calibration",shape:"line",points:[],value:n};$("drawGuide").textContent=`追加較正 ${n}m：2点を指定`;renderAnnotations()}
function openEditor(){const sf=activeSurface();if(!sf?.photoRef)return;$("setupPanel").classList.add("hidden");$("editorPanel").classList.remove("hidden");renderItemRail();loadStagePhoto();if(activeItemId)selectItem(activeItemId);renderSurfaceEntries();renderSurfaceStatus();}
function renderItemRail(){const sf=activeSurface(),s=currentSite();if(!sf)return;const items=sf.selectedItemIds.map(id=>s.items.find(i=>i.id===id)).filter(Boolean);const areaItems=items.filter(i=>i.unit==="㎡");$("itemRail").innerHTML=`<button class="chip utility" data-add-calibration>＋較正</button>`+items.map(i=>{const count=surfaceEntries(sf.id).filter(e=>e.itemId===i.id).length;return `<button class="chip ${!openingMode&&i.id===activeItemId?"selected":""} ${count?"done":""}" data-item="${i.id}">${esc(i.name)}${count?` ${count}`:""}</button>`}).join("")+(areaItems.length?`<button class="chip ${openingMode?"selected":""}" data-opening>サッシ・開口</button>`:"");const add=$("itemRail").querySelector("[data-add-calibration]");if(add)add.onclick=addCalibrationFromEditor;$("itemRail").querySelectorAll("[data-item]").forEach(b=>b.onclick=()=>selectItem(b.dataset.item));const ob=$("itemRail").querySelector("[data-opening]");if(ob)ob.onclick=selectOpeningTool;}
function autoShape(item){if(openingMode)return"quad";if(!item)return"point";if(/サッシ|窓|シャッター|扉|ドア/.test(item.name))return"quad";if(item.unit==="m")return"line";if(item.unit==="㎡")return activeAreaMode==="beam"?"line":"quad";return"point"}
function clearTransientInputs(){["areaH","areaW","directAreaQty","lengthValue","beamLength","beamH","beamW","entryMemo"].forEach(id=>{if($(id))$(id).value=""});if($("areaCount"))$("areaCount").value="1";if($("lengthCount"))$("lengthCount").value="1";if($("qtyValue"))$("qtyValue").value="1";if($("negativeEntry"))$("negativeEntry").checked=false;beamParts=[];renderBeamParts()}
function selectItem(id){const leavingOpening=openingMode;const switching=activeItemId&&activeItemId!==id;if(switching||leavingOpening)clearTransientInputs();openingMode=false;openingParentItemId="";$("areaCount").disabled=false;$("shapeMode").disabled=false;$("negativeEntry").disabled=false;activeItemId=id;const i=activeItem();if(!i)return;const pref=currentSite().itemPrefs[i.id]||{};activeAreaMode=i.unit==="㎡"?(pref.areaMode||(/梁/.test(i.name)?"beam":"rect")):"rect";draft={kind:"measure",shape:autoShape(i),points:[]};$("activeItemName").textContent=i.name;$("activeItemUnit").textContent=i.unit;$("areaInput").classList.toggle("hidden",i.unit!=="㎡");$("lengthInput").classList.toggle("hidden",i.unit!=="m");$("qtyInput").classList.toggle("hidden",i.unit==="㎡"||i.unit==="m");$("shapeMode").value="auto";loadItemPrefs(i);setAreaMode(activeAreaMode);updateDrawGuide();calcLive();renderItemRail();renderAnnotations();renderCaulkSuggestion();}

function selectOpeningTool(){
  const sf=activeSurface(),s=currentSite();if(!sf)return;
  const areaItems=sf.selectedItemIds.map(id=>s.items.find(i=>i.id===id)).filter(i=>i?.unit==="㎡");
  let parent=areaItems.find(i=>i.id===activeItemId);
  if(!parent&&areaItems.length===1)parent=areaItems[0];
  if(!parent&&areaItems.length>1)return alert("先に、サッシを控除する外壁・タイル等の㎡項目を選んでください。");
  if(!parent)return alert("開口を控除する㎡項目がこの面にありません。");
  if(!openingMode)clearTransientInputs();openingMode=true;openingParentItemId=parent.id;activeItemId=parent.id;activeAreaMode="rect";setAreaMode("rect");
  $("negativeEntry").checked=true;$("negativeEntry").disabled=true;$("areaCount").value="1";$("areaCount").disabled=true;$("shapeMode").disabled=true;draft={kind:"measure",shape:"quad",points:[]};
  $("activeItemName").textContent=`サッシ・開口 → ${parent.name}`;$("activeItemUnit").textContent="㎡控除";$("shapeMode").value="quad";
  $("areaInput").classList.remove("hidden");$("lengthInput").classList.add("hidden");$("qtyInput").classList.add("hidden");
  updateDrawGuide();calcLive();renderItemRail();renderAnnotations();renderCaulkSuggestion();
}
function loadItemPrefs(item){const p=currentSite().itemPrefs[item.id]||{};if(p.beamH!=null)$("beamH").value=p.beamH;if(p.beamW!=null)$("beamW").value=p.beamW;}
function saveItemPrefs(){const i=activeItem();if(!i)return;const p=currentSite().itemPrefs[i.id]||(currentSite().itemPrefs[i.id]={});if(i.unit==="㎡")p.areaMode=activeAreaMode;if($("beamLockSection").checked){p.beamH=Number($("beamH").value)||"";p.beamW=Number($("beamW").value)||""}else{delete p.beamH;delete p.beamW}}
function setAreaMode(mode){activeAreaMode=mode;document.querySelectorAll("[data-area-mode]").forEach(b=>b.classList.toggle("active",b.dataset.areaMode===mode));$("rectFields").classList.toggle("hidden",mode!=="rect");$("beamFields").classList.toggle("hidden",mode!=="beam");$("directAreaFields").classList.toggle("hidden",mode!=="direct");if(draft?.kind==="measure"&&activeItem()?.unit==="㎡"){draft.shape=autoShape(activeItem());draft.points=[]}updateDrawGuide();calcLive();renderAnnotations()}
function chosenShape(){const v=$("shapeMode").value;if(v!=="auto")return v;return autoShape(activeItem())}
function changeShape(){if(!draft||draft.kind!=="measure")draft={kind:"measure",shape:chosenShape(),points:[]};else{draft.shape=chosenShape();draft.points=[]}updateDrawGuide();renderAnnotations()}
function shapeNeed(shape){return shape==="line"?2:shape==="quad"?4:shape==="point"?1:3}
function pointDistance(a,b){return Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0))}
function orient(a,b,c){return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)}
function segIntersect(a,b,c,d){const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);return ((o1>0&&o2<0)||(o1<0&&o2>0))&&((o3>0&&o4<0)||(o3<0&&o4>0))}
function selfIntersects(points){const n=points.length;if(n<4)return false;for(let i=0;i<n;i++){const a=points[i],b=points[(i+1)%n];for(let j=i+1;j<n;j++){if(j===i||j===(i+1)%n||(i===0&&j===n-1))continue;const c=points[j],d=points[(j+1)%n];if(segIntersect(a,b,c,d))return true}}return false}
function validateDraftGeometry(d=draft){if(!d||!draftComplete())return"対象位置を完成させてください";if(d.shape==="line"&&pointDistance(d.points[0],d.points[1])<.004)return"線が短すぎます";if((d.shape==="quad"||d.shape==="polygon")&&selfIntersects(d.points))return"囲み線が交差しています。点の順番を直してください";return""}
function draftComplete(){if(!draft)return false;const n=draft.points.length;if(draft.shape==="polygon")return n>=3&&!!draft.closed;return n>=shapeNeed(draft.shape)}
