function updateDeleteSiteState(){
 const b=$("deleteSiteButton"),h=$("deleteSiteHint");if(!b||!h)return;
 const canDelete=state.sites.length>=2,target=currentSite(),label=target?.name||"名称未入力の現場";
 b.disabled=!canDelete;
 b.setAttribute("aria-disabled",String(!canDelete));
 if(canDelete){h.textContent=`「${label}」を削除できます。削除対象を必ず現場切替で確認してください。`;h.className="deleteHint ready"}
 else{h.textContent="保存現場が2件以上になると削除できます。最後の1現場は誤操作防止のため削除できません。";h.className="deleteHint"}
}
function renderSiteSwitcher(){const s=currentSite();$("siteSwitcher").innerHTML=state.sites.map((x,i)=>`<option value="${x.id}" ${x.id===s.id?"selected":""}>${esc(x.name||"名称未入力の現場 "+(i+1))}</option>`).join("")+`<option value="__new__">＋ 新しい現場を作る</option>`;updateDeleteSiteState()}
function syncSiteToUi(){const s=currentSite();$("siteName").value=s.name||"";$("siteDate").value=s.date||"";$("siteStaff").value=s.staff||"";$("siteAddress").value=s.address||"";$("siteMemo").value=s.memo||""}
function syncSiteFromUi(){const s=currentSite();s.name=$("siteName").value||"";s.date=$("siteDate").value||"";s.staff=$("siteStaff").value||"";s.address=$("siteAddress").value||"";s.memo=$("siteMemo").value||"";renderSiteSwitcher()}
function updateSaveGuide(text=$("saveState")?.textContent||"保存状態確認中",ok=!String(text).includes("失敗")){const e=$("guideSaveState");if(!e||!state.sites.length)return;const s=currentSite(),entryCount=s?.entries?.length||0;e.textContent=`${text}。現場 ${state.sites.length}件・この現場の実測 ${entryCount}件。現調完了時はバックアップ推奨です。`;e.className="guideState"+(ok?"":" warn")}
function setGuideState(id,text,ok){const e=$(id);if(!e)return;e.textContent=text;e.className="guideState"+(ok?"":" warn")}
function updateGuides(){const s=currentSite(),itemCount=s.items.filter(i=>String(i.name||"").trim()).length,entryCount=s.entries.length,totalCount=totals().length,siteNamed=!!String(s.name||"").trim();setGuideState("guideSiteState",siteNamed&&itemCount?`準備完了：拾い項目 ${itemCount}件。下部の「② 実測」へ進めます。`:`未完了：${siteNamed?"":"現場名を入力してください。"}${itemCount?"":" 拾い項目を1件以上登録してください。"}`,siteNamed&&itemCount>0);setGuideState("guideMeasureState",entryCount?`実測 ${entryCount}件登録済み。続けて実測するか「③ 集計」で確認してください。`:(itemCount?"実測はまだ0件です。項目を選んで寸法を入力してください。":"先に「① 現場」で拾い項目を登録してください。"),entryCount>0);setGuideState("guideResultState",entryCount?`集計可能：実測 ${entryCount}件・集計項目 ${totalCount}件。内容確認後「出力」を使用できます。`:"実測データがありません。「② 実測」で数量を登録してください。",entryCount>0);updateSaveGuide()}
function go(v){currentView=v;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v));document.querySelectorAll(".bottomNav button").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="measure")renderMeasure();if(v==="result")renderResults();if(v==="save")updateStorage();updateGuides();window.scrollTo({top:0,behavior:"smooth"})}
function itemHead(){return `<div class="sheetHead"><div class="cell">No.</div><div class="cell">項目名</div><div class="cell">単位</div><div class="cell">分類</div><div class="cell">メモ</div></div>`}
function itemRow(i,n){return `<div class="sheetRow" data-id="${i.id}"><div class="cell no">${n+1}</div><div class="cell"><input data-k="name" value="${esc(i.name)}" placeholder="項目名"></div><div class="cell"><select data-k="unit"><option ${i.unit==="㎡"?"selected":""}>㎡</option><option ${i.unit==="m"?"selected":""}>m</option><option ${i.unit==="箇所"?"selected":""}>箇所</option><option ${i.unit==="枚"?"selected":""}>枚</option><option ${i.unit==="式"?"selected":""}>式</option></select></div><div class="cell"><input data-k="group" value="${esc(i.group)}" placeholder="分類"></div><div class="cell"><input data-k="memo" value="${esc(i.memo)}" placeholder="測定ルール等"></div></div>`}
function syncEntriesForItem(item){const s=currentSite();for(const e of s.entries.filter(e=>e.itemId===item.id)){e.itemName=item.name;e.group=item.group||""}}
function ensureBlankItem(){const s=currentSite();if(!s.items.length||s.items[s.items.length-1].name.trim())s.items.push(blankItem())}
function renderItems(){ensureBlankItem();const s=currentSite();$("itemTable").innerHTML=itemHead()+s.items.map(itemRow).join("");renderMeasureItems()}
function renderMeasureItems(){const s=currentSite(),items=s.items.filter(i=>i.name.trim());$("measureItem").innerHTML=items.length?items.map(i=>`<option value="${i.id}">${esc(i.name)}（${esc(i.unit)}）</option>`).join(""):`<option value="">項目を登録してください</option>`;onMeasureItemChange()}
function renderMeasure(){renderMeasureItems();renderEntries();calcLive()}
function currentItem(){return currentSite().items.find(i=>i.id===$("measureItem").value)}
function onMeasureItemChange(){const i=currentItem(),u=i?.unit||"";$("measureUnit").value=u;$("areaFields").classList.toggle("hidden",u!=="㎡");$("lengthFields").classList.toggle("hidden",u!=="m");$("qtyFields").classList.toggle("hidden",u==="㎡"||u==="m"||!u);$("liveUnit").textContent=u;calcLive()}
function n(id,def=0){const v=parseFloat($(id).value);return Number.isFinite(v)?v:def}
function validCount(id){const raw=$(id).value.trim(),v=Number(raw);return raw!==""&&Number.isInteger(v)&&v>=1?v:null}
function calcBase(){const i=currentItem();if(!i)return{qty:0,formula:"項目未選択",valid:false,error:"項目を選択してください"};const u=i.unit;if(u==="㎡"){const mode=$("areaMode").value,a=n("areaA"),b=n("areaB"),c=n("areaC"),count=validCount("areaCount"),ded=n("areaDeduct");if(a<=0||b<=0||(mode==="around"&&c<=0))return{qty:0,formula:"",valid:false,error:"寸法は0より大きい値を入力してください"};if(count===null)return{qty:0,formula:"",valid:false,error:"同寸法数は1以上の整数で入力してください"};if(ded<0)return{qty:0,formula:"",valid:false,error:"控除は0以上で入力してください"};let gross=0,f="";if(mode==="around"){gross=(a+b)*2*c*count;f=`(${a}+${b})×2×${c}×${count}−${ded}`}else{gross=a*b*count;f=`${a}×${b}×${count}−${ded}`}const q=round3(gross-ded);return{qty:q,formula:f,valid:gross>0&&q>=0,error:q<0?"控除が計算前数量を超えています":""}}if(u==="m"){const l=n("lengthValue"),count=validCount("lengthCount"),ded=n("lengthDeduct");if(l<=0)return{qty:0,formula:"",valid:false,error:"長さは0より大きい値を入力してください"};if(count===null)return{qty:0,formula:"",valid:false,error:"同寸法数は1以上の整数で入力してください"};if(ded<0)return{qty:0,formula:"",valid:false,error:"控除は0以上で入力してください"};const q=round3(l*count-ded);return{qty:q,formula:`${l}×${count}−${ded}`,valid:q>=0,error:q<0?"控除が計算前数量を超えています":""}}const q=round3(n("qtyValue"));return{qty:q,formula:String(q),valid:q>0,error:"数量は0より大きい値を入力してください"}}
function applyEntrySign(r){if(!r.valid||!$("negativeEntry")?.checked)return r;return{...r,qty:-Math.abs(r.qty),formula:`−（${r.formula}）`,isNegative:true}}function calc(){return applyEntrySign(calcBase())}function calcLive(){const r=calc();$("liveQty").textContent=r.qty.toFixed(3);$("liveFormula").textContent=r.error||("式："+r.formula);$("calcPanel")?.classList.toggle("negativeMode",!!r.isNegative)}
function updateAreaLabels(){const m=$("areaMode").value,around=m==="around";$("cField").classList.toggle("hidden",!around);$("aLabel").textContent=around?"長さ（m）":m==="floor"?"長さ（m）":"縦・高さ（m）";$("bLabel").textContent=around?"奥行き（m）":m==="floor"?"奥行き（m）":"横・幅（m）";calcLive()}
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
async function compress(file){const src=await readFile(file);return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{const ratio=Math.min(1,MAX_SIDE/im.naturalWidth,MAX_SIDE/im.naturalHeight),w=Math.max(1,Math.round(im.naturalWidth*ratio)),h=Math.max(1,Math.round(im.naturalHeight*ratio)),c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d",{alpha:false});x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(im,0,0,w,h);res(c.toDataURL("image/jpeg",JPEG_QUALITY))};im.onerror=()=>rej(new Error("画像読込失敗"));im.src=src})}
function renderPendingPhotos(){$("photoPreview").innerHTML=pendingPhotos.map(p=>`<div class="thumb"><img src="${p}"></div>`).join("")}
async function registerEntry(){const i=currentItem(),r=calc();if(!i)return alert("先に拾い項目を登録してください。");if(!r.valid)return alert(r.error||"数量を正しく入力してください。");const refs=[];try{for(const p of pendingPhotos)refs.push(await storePhotoData(p))}catch(err){return alert("写真を保存できませんでした："+(err.message||err))}const e={id:uid(),itemId:i.id,itemName:i.name,unit:i.unit,group:i.group||"",quantity:r.qty,formula:r.formula,isNegative:!!r.isNegative,memo:$("entryMemo").value||"",photos:refs,createdAt:new Date().toISOString()};currentSite().entries.push(e);await saveNow();clearMeasure();renderEntries();renderResults();updateGuides();setSaveState("実測登録済み",true);const b=$("registerEntryButton");b.textContent="登録しました";setTimeout(()=>{setSaveState("保存済み",true);b.textContent="実測を登録"},1200)}
function clearMeasure(){["areaA","areaB","areaC","lengthValue","entryMemo"].forEach(id=>$(id).value="");["areaCount","lengthCount","qtyValue"].forEach(id=>$(id).value="1");["areaDeduct","lengthDeduct"].forEach(id=>$(id).value="0");pendingPhotos=[];$("entryPhotos").value="";$("negativeEntry").checked=false;renderPendingPhotos();calcLive()}
function entryHead(){return `<div class="sheetHead"><div class="cell">No.</div><div class="cell">項目</div><div class="cell">単位</div><div class="cell">数量</div><div class="cell">写真</div><div class="cell">式・メモ</div><div class="cell"></div></div>`}
function entryPhotoHtml(e){const ps=Array.isArray(e.photos)?e.photos:[];if(!ps.length)return `<div class="entryPhotos"><span class="entryPhotoMore">なし</span></div>`;return `<div class="entryPhotos">${ps.slice(0,2).map(p=>`<div class="entryThumb"><img src="${photoSrc(p)}" alt="実測写真"></div>`).join("")}${ps.length>2?`<span class="entryPhotoMore">+${ps.length-2}</span>`:""}</div>`}
function entryRow(e,n){return `<div class="sheetRow" data-entry-id="${e.id}"><div class="cell no">${n+1}</div><div class="cell"><input value="${esc(e.itemName)}" readonly></div><div class="cell"><input value="${esc(e.unit)}" readonly></div><div class="cell"><input value="${e.quantity}" readonly></div><div class="cell">${entryPhotoHtml(e)}</div><div class="cell"><input value="${esc(e.formula+(e.memo?"／"+e.memo:""))}" readonly></div><div class="cell action"><button class="rowMenu" data-entry-menu="${e.id}">…</button></div></div>`}
function renderEntries(){const es=currentSite().entries;$("entryTable").innerHTML=entryHead()+(es.length?es.map(entryRow).join(""):`<div class="info" style="padding:16px">実測履歴はありません。</div>`)}
function totals(){const s=currentSite(),m=new Map();for(const e of s.entries){const item=s.items.find(i=>i.id===e.itemId),name=item?.name||e.itemName,unit=e.unit,group=item?.group||e.group||"",k=e.itemId+"|"+unit;if(!m.has(k))m.set(k,{name,unit,qty:0,group,count:0});const x=m.get(k);x.name=name;x.group=group;x.qty=round3(x.qty+Number(e.quantity||0));x.count++}return[...m.values()]}
function renderResults(){const s=currentSite(),t=totals();$("resultStatus").className="status"+(t.length?"":" warn");$("resultStatus").textContent=t.length?`集計項目 ${t.length}件・実測 ${s.entries.length}件。`:`実測データがありません。`;$("resultTable").innerHTML=`<div class="resultHead"><div>項目</div><div>単位</div><div>合計</div><div>分類・回数</div></div>`+t.map(x=>`<div class="resultRow"><div>${esc(x.name)}</div><div>${esc(x.unit)}</div><div><b>${x.qty.toFixed(3)}</b></div><div>${esc(x.group)}・${x.count}回</div></div>`).join("");$("printSiteName").textContent=s.name||"";$("printSiteDate").textContent=s.date||"";$("printAddress").textContent=s.address||"";$("printStaff").textContent=s.staff||"";$("printDetails").innerHTML=`<table class="detailPrint"><thead><tr><th>No.</th><th>項目</th><th>単位</th><th>数量</th><th>算定式</th><th>メモ</th><th>写真</th></tr></thead><tbody>${s.entries.map((e,i)=>{const item=s.items.find(x=>x.id===e.itemId),ps=Array.isArray(e.photos)?e.photos:[];return `<tr><td>${i+1}</td><td>${esc(item?.name||e.itemName)}</td><td>${esc(e.unit)}</td><td>${Number(e.quantity||0).toFixed(3)}</td><td>${esc(e.formula)}</td><td>${esc(e.memo)}</td><td><div class="printPhotos">${ps.map(p=>`<img src="${photoSrc(p)}" alt="実測写真">`).join("")}</div></td></tr>`}).join("")}</tbody></table>`;updateGuides()}
