function showSheet(title,buttons){$("sheetRoot").innerHTML=`<div class="sheetBackdrop" id="sheetBackdrop"><div class="sheet"><h3>${esc(title)}</h3>${buttons.map((b,i)=>`<button class="${b.cls||""}" data-sheet-i="${i}">${esc(b.label)}</button>`).join("")}<button data-sheet-close>閉じる</button></div></div>`;$("sheetBackdrop").onclick=e=>{if(e.target.id==="sheetBackdrop"||e.target.hasAttribute("data-sheet-close"))closeSheet()};document.querySelectorAll("[data-sheet-i]").forEach(x=>x.onclick=()=>{const b=buttons[Number(x.dataset.sheetI)];closeSheet();b.run()})}
function closeSheet(){$("sheetRoot").innerHTML=""}
function csvCell(v){let s=String(v??"");if(/^[=+\-@\t\r]/.test(s))s="'"+s;return/[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},900)}
function safeName(s){return(s||"現調台帳").replace(/[\\/:*?\"<>|\s]+/g,"_")}
function outputAudit(){const s=currentSite(),issues=[];if(!String(s.name||"").trim())issues.push("現場名が未入力です");if(!s.entries.length)issues.push("実測データがありません");s.entries.forEach((e,i)=>{const item=s.items.find(x=>x.id===e.itemId);if(!String(item?.name||e.itemName||"").trim())issues.push(`実測No.${i+1}の項目名が未入力です`);const q=Number(e.quantity);if(!Number.isFinite(q)||q===0)issues.push(`実測No.${i+1}の数量が不正です`)});return issues}
function exportCsv(){const issues=outputAudit();if(issues.length)return alert(issues.join("\n"));const s=currentSite(),rows=[["現場名",s.name],["現調日",s.date],["担当者",s.staff],["工事場所",s.address],[],["No.","項目","分類","単位","数量","算定式","メモ","写真枚数"]];s.entries.forEach((e,i)=>{const item=s.items.find(x=>x.id===e.itemId);rows.push([i+1,item?.name||e.itemName,item?.group||e.group,e.unit,e.quantity,e.formula,e.memo,Array.isArray(e.photos)?e.photos.length:0])});download(new Blob(["\ufeff"+rows.map(r=>r.map(csvCell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),safeName(s.name)+"_現調数量.csv")}
async function sha256(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function collectBackupPhotos(data){const photos={};for(const ref of [...new Set(allPhotoRefs(data))]){const src=isDataUrl(ref)?ref:await photoGet(ref);if(src)photos[ref]=src}return photos}
async function exportBackup(all){syncSiteFromUi();const data=structuredClone(all?state:{schemaVersion:SCHEMA_VERSION,updatedAt:state.updatedAt,currentSiteId:state.currentSiteId,sites:[currentSite()]}),photos=await collectBackupPhotos(data),raw=JSON.stringify({data,photos}),payload={schema:"field-survey-ledger",schemaVersion:2,exportedAt:new Date().toISOString(),scope:all?"all":"current",checksum:await sha256(raw),data,photos};download(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),safeName(all?"全現場":currentSite().name)+"_現調台帳バックアップ.json")}
async function importBackup(file){const p=JSON.parse(await file.text());if(p.schema!=="field-survey-ledger"||!p.data)throw new Error("対応していないバックアップです");const v=Number(p.schemaVersion||1),photoBundle=p.photos&&typeof p.photos==="object"?p.photos:{};const raw=v>=2?JSON.stringify({data:p.data,photos:photoBundle}):JSON.stringify(p.data);if(p.checksum&&await sha256(raw)!==p.checksum)throw new Error("バックアップの整合性が一致しません");if(!confirm("バックアップを復元します。現在のデータへ追加されます。よろしいですか？"))return;const imported=normalize(p.data),incoming=[];for(const s of imported.sites){const itemMap=new Map(),items=s.items.map(i=>{const nid=uid();itemMap.set(i.id,nid);return{...i,id:nid}}),entries=[];for(const e of s.entries){const refs=[];for(const ref of Array.isArray(e.photos)?e.photos:[]){const data=isDataUrl(ref)?ref:photoBundle[ref];if(data)refs.push(await storePhotoData(data));else if(v>=2)throw new Error("バックアップ内の写真データが不足しています")}entries.push({...e,id:uid(),itemId:itemMap.get(e.itemId)||e.itemId,photos:refs})}incoming.push({...s,id:uid(),items,entries})}state.sites.push(...incoming);state.currentSiteId=incoming[0]?.id||state.currentSiteId;syncSiteToUi();renderAll();await saveNow();alert(v>=2?"復元しました。":"旧形式バックアップを互換復元しました。")}
function showOutput(){const issues=outputAudit();if(issues.length)return alert(issues.join("\n"));showSheet("出力方法",[{label:"PDF・印刷",cls:"primary",run:()=>{renderResults();window.print()}},{label:"CSV出力",run:exportCsv},{label:"集計をコピー",run:async()=>{const text=totals().map(x=>`${x.name}\t${x.qty.toFixed(3)} ${x.unit}`).join("\n");await navigator.clipboard.writeText(text);alert("集計をコピーしました。")}}])}
function showItemMenu(id){const s=currentSite(),i=s.items.find(x=>x.id===id);if(!i)return;showSheet(i.name||"空の項目",[{label:"この項目を削除",cls:"danger",run:()=>{if(s.entries.some(e=>e.itemId===id))return alert("実測履歴がある項目は削除できません。");s.items=s.items.filter(x=>x.id!==id);renderItems();saveSoon()}}])}
function showEntryMenu(id){const s=currentSite(),e=s.entries.find(x=>x.id===id);if(!e)return;showSheet(e.itemName,[{label:"この実測を削除",cls:"danger",run:async()=>{if(!confirm("この実測を削除しますか？"))return;await deletePhotoRefs(e.photos);s.entries=s.entries.filter(x=>x.id!==id);renderEntries();renderResults();await saveNow()}}])}
async function updateStorage(){const metaBytes=new Blob([JSON.stringify(state)]).size,photoBytes=[...photoCache.values()].reduce((a,x)=>a+Math.round(((String(x).split(",")[1]||"").length*3)/4),0),total=metaBytes+photoBytes;let t=`現場 ${state.sites.length}件・実測 ${state.sites.reduce((a,s)=>a+s.entries.length,0)}件・写真 ${allPhotoRefs().length}枚・保存データ約 ${(total/1024/1024).toFixed(1)}MB。`;if(navigator.storage?.estimate)try{const e=await navigator.storage.estimate();if(e.quota)t+=` 端末割当使用率 ${(e.usage/e.quota*100).toFixed(1)}%。`}catch{}$("storageInfo").textContent=t}
function renderAll(){renderSiteSwitcher();syncSiteToUi();renderItems();renderMeasure();renderResults();updateStorage();updateGuides()}
function newSiteAction(){const s=newSite();state.sites.push(s);state.currentSiteId=s.id;renderAll();saveSoon();go("site")}
async function deleteSiteAction(){if(state.sites.length<=1){updateDeleteSiteState();return;}const target=currentSite(),label=target.name||"名称未入力の現場";if(!confirm(`現在選択中の「${label}」を削除しますか？\nこの現場の実測・写真も削除されます。`))return;await deletePhotoRefs(target.entries.flatMap(e=>e.photos||[]));state.sites=state.sites.filter(s=>s.id!==state.currentSiteId);state.currentSiteId=state.sites[0].id;renderAll();await saveNow()}
async function resetAll(){if(!confirm("端末内の全現場データを初期化します。バックアップがない場合は戻せません。"))return;await clearAllPhotos();state=normalize({schemaVersion:SCHEMA_VERSION,sites:[newSite()]});renderAll();await saveNow()}
SITE_FIELDS.forEach(id=>$(id).addEventListener("input",()=>{syncSiteFromUi();updateGuides();saveSoon()}));$("siteSwitcher").onchange=e=>{
  const selected=e.target.value;
  syncSiteFromUi();
  if(selected==="__new__"){newSiteAction();return;}
  state.currentSiteId=selected;renderAll();saveSoon();
};$("itemTable").addEventListener("input",e=>{const row=e.target.closest(".sheetRow"),i=currentSite().items.find(x=>x.id===row?.dataset.id),k=e.target.dataset.k;if(i&&k){i[k]=e.target.value;syncEntriesForItem(i);renderEntries();renderResults();saveSoon()}});$("itemTable").addEventListener("change",e=>{const row=e.target.closest(".sheetRow"),i=currentSite().items.find(x=>x.id===row?.dataset.id),k=e.target.dataset.k;if(i&&k){i[k]=e.target.value;syncEntriesForItem(i);ensureBlankItem();renderItems();renderEntries();renderResults();saveSoon()}});$("entryTable").onclick=e=>{const b=e.target.closest("[data-entry-menu]");if(b)showEntryMenu(b.dataset.entryMenu)};
["measureItem","areaMode","areaA","areaB","areaC","areaCount","areaDeduct","lengthValue","lengthCount","lengthDeduct","qtyValue"].forEach(id=>$(id).addEventListener("input",id==="areaMode"?updateAreaLabels:calcLive));$("negativeEntry").onchange=calcLive;$("measureItem").onchange=onMeasureItemChange;$("areaMode").onchange=updateAreaLabels;$("entryPhotos").onchange=async e=>{pendingPhotos=[];for(const f of [...e.target.files].slice(0,6))pendingPhotos.push(await compress(f));renderPendingPhotos()};$("registerEntryButton").onclick=registerEntry;$("outputButton").onclick=showOutput;$("deleteSiteButton").onclick=deleteSiteAction;$("backupButton").onclick=()=>showSheet("バックアップ範囲",[{label:"選択中の現場を書き出す",cls:"primary",run:()=>exportBackup(false)},{label:"全現場を書き出す",run:()=>exportBackup(true)}]);$("importButton").onclick=()=>$("importFile").click();$("importFile").onchange=async e=>{try{if(e.target.files[0])await importBackup(e.target.files[0])}catch(err){alert("復元できませんでした："+(err.message||err))}e.target.value=""};$("resetAllButton").onclick=resetAll;document.querySelectorAll(".bottomNav button").forEach(b=>b.onclick=()=>go(b.dataset.view));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden"){syncSiteFromUi();saveNow().catch(()=>{})}});window.addEventListener("pagehide",()=>{syncSiteFromUi();saveNow().catch(()=>{})});
(async()=>{try{await load();renderAll();updateAreaLabels();setSaveState(bootRecoverySource?"復旧済み・保存確認済み":"保存済み",true);if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js").catch(()=>{})}catch(e){setSaveState("保存エラー",false);alert("端末保存を開始できませんでした："+(e.message||e))}})();
