"use strict";
const DB_NAME="field_survey_ledger_db",DB_VERSION=2,STORE="app",RECOVERY_STORE="recovery",PHOTO_STORE="photos",KEY="state",RECOVERY_KEY="latest",EMERGENCY_KEY="field_survey_ledger_emergency_v2",SCHEMA_VERSION=2,MAX_SIDE=1600,JPEG_QUALITY=.78;
const $=id=>document.getElementById(id),round3=n=>Math.round((Number(n)||0)*1000)/1000,uid=()=>crypto.randomUUID?crypto.randomUUID():"id_"+Date.now()+"_"+Math.random().toString(16).slice(2),esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const SITE_FIELDS=["siteName","siteDate","siteStaff","siteAddress","siteMemo"];
let db=null,saveTimer=null,pendingPhotos=[],currentView="site",photoCache=new Map(),bootRecoverySource="";
let state={schemaVersion:SCHEMA_VERSION,updatedAt:"",currentSiteId:"",sites:[]};
function blankItem(){return{id:uid(),name:"",unit:"㎡",group:"",memo:""}}
function newSite(){const id=uid();return{id,name:"",date:new Date().toISOString().slice(0,10),staff:"",address:"",memo:"",items:[{id:uid(),name:"外壁",unit:"㎡",group:"塗装",memo:""},{id:uid(),name:"軒天",unit:"㎡",group:"塗装",memo:""},{id:uid(),name:"破風",unit:"m",group:"付帯",memo:""},{id:uid(),name:"横樋",unit:"m",group:"付帯",memo:""},{id:uid(),name:"竪樋",unit:"m",group:"付帯",memo:""},blankItem()],entries:[]}}
function currentSite(){return state.sites.find(s=>s.id===state.currentSiteId)||state.sites[0]}
function normalize(raw){const src=raw&&typeof raw==="object"?raw:{};const n={...state,...src,schemaVersion:SCHEMA_VERSION};n.sites=Array.isArray(src.sites)?src.sites.map(s=>({...newSite(),...s,items:Array.isArray(s.items)?s.items.map(i=>({...blankItem(),...i})):[],entries:Array.isArray(s.entries)?s.entries.map(e=>({...e,photos:Array.isArray(e.photos)?e.photos:[]})):[]})):[];if(!n.sites.length)n.sites=[newSite()];if(!n.sites.some(s=>s.id===n.currentSiteId))n.currentSiteId=n.sites[0].id;return n}
function validState(v){return!!(v&&typeof v==="object"&&Array.isArray(v.sites))}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE);if(!d.objectStoreNames.contains(RECOVERY_STORE))d.createObjectStore(RECOVERY_STORE);if(!d.objectStoreNames.contains(PHOTO_STORE))d.createObjectStore(PHOTO_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbGet(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readonly"),r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbPut(store,key,value){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readwrite"),r=tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error)})}
function idbDelete(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function idbClear(store){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function idbGetAllKeys(store){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readonly"),r=tx.objectStore(store).getAllKeys();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function readEmergency(){try{const x=JSON.parse(localStorage.getItem(EMERGENCY_KEY)||"null");return validState(x?.state)?x:null}catch{return null}}
function writeEmergencySnapshot(){try{localStorage.setItem(EMERGENCY_KEY,JSON.stringify({schemaVersion:SCHEMA_VERSION,updatedAt:state.updatedAt||new Date().toISOString(),state}))}catch{}}
function isDataUrl(v){return typeof v==="string"&&v.startsWith("data:image/")}
function photoSrc(ref){return isDataUrl(ref)?ref:(photoCache.get(ref)||"")}
async function photoGet(id){if(!id||isDataUrl(id))return isDataUrl(id)?id:"";if(photoCache.has(id))return photoCache.get(id);const d=await idbGet(PHOTO_STORE,id);if(d)photoCache.set(id,d);return d||""}
async function storePhotoData(data,id=uid()){if(!isDataUrl(data))throw new Error("写真データ形式が不正です");await idbPut(PHOTO_STORE,id,data);photoCache.set(id,data);return id}
function allPhotoRefs(data=state){const a=[];for(const s of data.sites||[])for(const e of s.entries||[])for(const p of e.photos||[])if(typeof p==="string")a.push(p);return a}
async function hydratePhotoCache(){for(const id of [...new Set(allPhotoRefs().filter(x=>!isDataUrl(x)))])await photoGet(id)}
async function migrateInlinePhotos(){let changed=false;for(const site of state.sites)for(const e of site.entries){const refs=[];for(const p of Array.isArray(e.photos)?e.photos:[]){if(isDataUrl(p)){refs.push(await storePhotoData(p));changed=true}else if(p&&typeof p==="object"&&isDataUrl(p.data)){refs.push(await storePhotoData(p.data,p.id||uid()));changed=true}else if(typeof p==="string")refs.push(p)}e.photos=refs}return changed}
async function cleanupOrphanPhotos(){const used=new Set(allPhotoRefs().filter(x=>!isDataUrl(x))),keys=await idbGetAllKeys(PHOTO_STORE);for(const k of keys)if(!used.has(k)){await idbDelete(PHOTO_STORE,k);photoCache.delete(k)}}
async function deletePhotoRefs(refs){for(const r of refs||[])if(typeof r==="string"&&!isDataUrl(r)){await idbDelete(PHOTO_STORE,r).catch(()=>{});photoCache.delete(r)}}
async function clearAllPhotos(){photoCache.clear();await idbClear(PHOTO_STORE)}
function updatedMs(v){const t=Date.parse(v?.updatedAt||"");return Number.isFinite(t)?t:0}
function setSaveState(text,ok=true){const e=$("saveState");if(e)e.textContent=text;updateSaveGuide(text,ok)}
async function load(){db=await openDb();const primary=await idbGet(STORE,KEY).catch(()=>null),recRaw=await idbGet(RECOVERY_STORE,RECOVERY_KEY).catch(()=>null),recovery=recRaw?.state||recRaw,em=readEmergency();const candidates=[{source:"primary",value:primary},{source:"recovery",value:recovery},{source:"emergency",value:em?.state}].filter(x=>validState(x.value)).sort((a,b)=>updatedMs(b.value)-updatedMs(a.value));const chosen=candidates[0];state=normalize(chosen?.value||state);bootRecoverySource=chosen&&chosen.source!=="primary"?chosen.source:"";const migrated=await migrateInlinePhotos();await hydratePhotoCache();await cleanupOrphanPhotos();if(!chosen||chosen.source!=="primary"||migrated||Number(chosen.value?.schemaVersion||1)<SCHEMA_VERSION)await saveNow({quiet:true})}
function saveSoon(){clearTimeout(saveTimer);setSaveState("保存中…",true);saveTimer=setTimeout(()=>saveNow().catch(()=>{}),350)}
function saveNow(options={}){state.schemaVersion=SCHEMA_VERSION;state.updatedAt=new Date().toISOString();writeEmergencySnapshot();const snapshot=structuredClone(state);return new Promise((resolve,reject)=>{if(!db)return reject(new Error("DB未接続"));const tx=db.transaction([STORE,RECOVERY_STORE],"readwrite");tx.objectStore(STORE).put(snapshot,KEY);tx.objectStore(RECOVERY_STORE).put({state:snapshot,savedAt:state.updatedAt},RECOVERY_KEY);tx.oncomplete=()=>{if(!options.quiet)setSaveState("保存済み",true);updateStorage();resolve()};tx.onerror=()=>{setSaveState("保存失敗・復旧用保持",false);reject(tx.error)};tx.onabort=()=>{setSaveState("保存失敗・復旧用保持",false);reject(tx.error||new Error("保存処理が中断されました"))}})}
