const STORE='genchou_note_sites_v5';
const OLD_STORES=['genchou_note_sites_v4','genchou_note_sites_v3','genchou_note_sites_v2'];
const TPL_STORE='genchou_note_templates_v1';
const units=['㎡','m','箇所','枚','式'];
let db={sites:[],currentId:null};
let entryPhotoData=[];
let edit={type:null,id:null};
let historyCollapsed=false;
const $=id=>document.getElementById(id);
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,9)}
function today(){return new Date().toISOString().slice(0,10)}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n,unit){const v=Number(n)||0;return (unit==='箇所'||unit==='枚')?v.toFixed(0):v.toFixed(2)}
function sameOptions(v=1){let h='';for(let i=1;i<=9;i++)h+=`<option value="${i}" ${Number(v)===i?'selected':''}>×${i}</option>`;return h}
function save(){localStorage.setItem(STORE,JSON.stringify(db))}
function safeSave(){try{save();return true}catch(e){alert('保存容量を超えました。写真を減らすか、バックアップ後に整理してください。');return false}}
function load(){try{db=JSON.parse(localStorage.getItem(STORE))||null;for(const k of OLD_STORES){if(!db)db=JSON.parse(localStorage.getItem(k))||null}}catch(e){}if(!db||!Array.isArray(db.sites))db={sites:[],currentId:null};$('siteDate').value=today();renderAll()}
function currentSite(){return db.sites.find(s=>s.id===db.currentId)||null}
function currentView(){return document.querySelector('.view.active')?.id?.replace('view-','')||'sites'}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+name).classList.add('active');document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));$('tab-'+name).classList.add('active');renderAll();if(name==='measure')setTimeout(()=>onMeasureItemChange(),0)}
function renderFooter(){const v=currentView();const h={sites:'<button class="primary" onclick="submitSite()">現場登録</button><button onclick="showView(\'items\')">項目へ</button><button class="blue" onclick="showView(\'tools\')">保管</button>',items:'<button class="primary" onclick="submitItem()">項目登録</button><button class="blue" onclick="showView(\'measure\')">実測へ</button><button onclick="addDefaultTemplates()">定番追加</button>',measure:'<button class="primary" onclick="submitEntry(false)">登録</button><button class="ok" onclick="submitEntry(true)">続けて</button><button class="blue" onclick="showView(\'result\')">結果</button>',result:'<button class="blue" onclick="copyResultText()">コピー</button><button class="blue" onclick="exportCsv()">CSV</button><button class="danger" onclick="deleteCurrentSite()">現場削除</button>',tools:'<button class="primary" onclick="exportCurrentSiteJson()">現場保存</button><button class="blue" onclick="exportAllJson()">全保存</button><button onclick="importJsonClick()">復元</button>'};$('footerBar').innerHTML=h[v]||h.sites}
function clearSiteForm(){edit={type:null,id:null};$('siteSubmit').textContent='この現場を登録';$('siteName').value='';$('siteDate').value=today();$('siteStaff').value='';$('siteAddress').value='';$('siteMemo').value=''}
function submitSite(){return edit.type==='site'?updateSite():createSite()}
function createSite(){const name=$('siteName').value.trim();if(!name){alert('現場名を入力してください');return}const site={id:uid(),name,date:$('siteDate').value||today(),staff:$('siteStaff').value.trim(),address:$('siteAddress').value.trim(),memo:$('siteMemo').value.trim(),items:[],entries:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.sites.unshift(site);db.currentId=site.id;if(!safeSave())return;clearSiteForm();renderAll();showView('items')}
function startEditSite(id){const s=db.sites.find(x=>x.id===id);if(!s)return;db.currentId=id;edit={type:'site',id};$('siteName').value=s.name;$('siteDate').value=s.date||today();$('siteStaff').value=s.staff||'';$('siteAddress').value=s.address||'';$('siteMemo').value=s.memo||'';$('siteSubmit').textContent='現場を更新';showView('sites');setTimeout(()=>$('siteName').scrollIntoView({block:'center'}),50)}
function updateSite(){const s=db.sites.find(x=>x.id===edit.id);if(!s)return;const name=$('siteName').value.trim();if(!name){alert('現場名を入力してください');return}s.name=name;s.date=$('siteDate').value||today();s.staff=$('siteStaff').value.trim();s.address=$('siteAddress').value.trim();s.memo=$('siteMemo').value.trim();s.updatedAt=new Date().toISOString();db.currentId=s.id;if(!safeSave())return;clearSiteForm();renderAll()}
function selectSite(id){db.currentId=id;safeSave();renderAll()}
function cloneSiteWithNewIds(site,keepEntries=true){const itemMap={};const ns=JSON.parse(JSON.stringify(site));ns.id=uid();ns.items=(ns.items||[]).map(i=>{const old=i.id;const ni={...i,id:uid(),createdAt:i.createdAt||new Date().toISOString()};itemMap[old]=ni.id;return ni});ns.entries=keepEntries?(ns.entries||[]).map(e=>({...e,id:uid(),itemId:itemMap[e.itemId]||e.itemId,createdAt:e.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()})):[];ns.createdAt=new Date().toISOString();ns.updatedAt=ns.createdAt;return ns}
function duplicateSite(id){const s=db.sites.find(x=>x.id===id);if(!s)return;const ns=cloneSiteWithNewIds(s,false);ns.name=s.name+' コピー';db.sites.unshift(ns);db.currentId=ns.id;if(!safeSave())return;renderAll();showView('items')}
function deleteSite(id){const s=db.sites.find(x=>x.id===id);if(!s)return;if(confirm('現場「'+s.name+'」を削除します。項目・実測・写真も削除されます。')){db.sites=db.sites.filter(x=>x.id!==id);if(db.currentId===id)db.currentId=db.sites[0]?.id||null;safeSave();renderAll();showView('sites')}}
function deleteCurrentSite(){const s=currentSite();if(s)deleteSite(s.id)}
function clearItemForm(){edit={type:null,id:null};$('itemSubmit').textContent='項目を登録';$('itemName').value='';$('itemUnit').value='㎡';$('itemGroup').value='';$('itemMemo').value=''}
function submitItem(){return edit.type==='item'?updateItem():createItem()}
function createItem(name,unit,group,memo){const s=currentSite();if(!s){alert('先に現場を選択してください');return null}const itemName=(name||$('itemName').value).trim();const itemUnit=unit||$('itemUnit').value;if(!itemName){alert('項目名を入力してください');return null}const item={id:uid(),name:itemName,unit:itemUnit,group:(group??$('itemGroup').value).trim(),memo:(memo??$('itemMemo').value).trim(),createdAt:new Date().toISOString()};s.items.push(item);s.updatedAt=new Date().toISOString();if(!safeSave())return null;clearItemForm();renderAll();return item}
function startEditItem(id){const i=itemById(id);if(!i)return;edit={type:'item',id};$('itemName').value=i.name;$('itemUnit').value=i.unit;$('itemGroup').value=i.group||'';$('itemMemo').value=i.memo||'';$('itemSubmit').textContent='項目を更新';showView('items');setTimeout(()=>$('itemName').scrollIntoView({block:'center'}),50)}
function updateItem(){const s=currentSite();const i=itemById(edit.id);if(!s||!i)return;const name=$('itemName').value.trim();if(!name){alert('項目名を入力してください');return}i.name=name;i.unit=$('itemUnit').value;i.group=$('itemGroup').value.trim();i.memo=$('itemMemo').value.trim();s.entries.filter(e=>e.itemId===i.id).forEach(e=>{e.itemName=i.name;e.unit=i.unit});s.updatedAt=new Date().toISOString();if(!safeSave())return;clearItemForm();renderAll()}
function deleteItem(id){const s=currentSite();if(!s)return;const used=s.entries.some(e=>e.itemId===id);if(confirm(used?'この項目の実測データも削除されます。削除しますか？':'この項目を削除しますか？')){s.items=s.items.filter(i=>i.id!==id);s.entries=s.entries.filter(e=>e.itemId!==id);safeSave();renderAll()}}
function quickCreateItem(){const name=prompt('追加する項目名を入力してください');if(!name)return;const unit=prompt('単位を入力してください：㎡ / m / 箇所 / 枚 / 式','㎡');if(!units.includes(unit)){alert('単位は ㎡、m、箇所、枚、式 のいずれかです');return}const item=createItem(name,unit,'','');if(item){$('measureItem').value=item.id;onMeasureItemChange()}}
function itemById(id){const s=currentSite();return s?.items.find(i=>i.id===id)||null}
function updateGroupFilter(){const s=currentSite();const sel=$('groupFilter');const val=sel.value;const groups=[...new Set((s?.items||[]).map(i=>i.group).filter(Boolean))];sel.innerHTML='<option value="">分類すべて</option>'+groups.map(g=>'<option value="'+escapeHtml(g)+'">'+escapeHtml(g)+'</option>').join('');if(groups.includes(val))sel.value=val}
function filteredItems(){const s=currentSite();if(!s)return[];const q=($('itemSearch')?.value||'').trim().toLowerCase();const g=$('groupFilter')?.value||'';return s.items.filter(i=>(!g||i.group===g)&&(!q||(i.name+i.group+i.memo).toLowerCase().includes(q)))}
function onMeasureItemChange(){const item=itemById($('measureItem').value);$('selectedUnit').textContent='単位：'+(item?.unit||'-');['areaFields','lenFields','qtyFields'].forEach(id=>$(id).classList.add('hidden'));if(item?.unit==='㎡'){$('areaFields').classList.remove('hidden');onAreaModeChange()}else if(item?.unit==='m')$('lenFields').classList.remove('hidden');else if(item)$('qtyFields').classList.remove('hidden');calcLive()}
function onAreaModeChange(){const mode=$('areaMode').value;const three=mode!=='flat';$('areaFlatFields').classList.toggle('hidden',three);$('area3dFields').classList.toggle('hidden',!three);const text={flat:'式：縦・高さ × 横・幅 × 同寸法数 − 控除',face:'式：長さ × 高さ × 同寸法数 − 控除',floor:'式：長さ × 奥行き × 同寸法数 − 控除',around:'式：（長さ＋奥行き）×2×高さ×同寸法数 − 控除'};$('areaModeHint').textContent=text[mode]}
function addDeduction(unit='㎡',d={}){if(unit!=='㎡')return;const div=document.createElement('div');div.className='deductRow';div.innerHTML='<div class="row3"><div><label>控除 縦</label><input class="dedH" type="number" step="0.001" inputmode="decimal" value="'+(d.h||'')+'" oninput="calcLive()"></div><div><label>控除 横</label><input class="dedW" type="number" step="0.001" inputmode="decimal" value="'+(d.w||'')+'" oninput="calcLive()"></div><div><label>数</label><select class="dedQ" onchange="calcLive()">'+sameOptions(d.q||1)+'</select></div></div><div class="row"><div><label>控除名</label><input class="dedName" placeholder="窓・扉など" value="'+escapeHtml(d.name||'')+'"></div><div><label>削除</label><button class="miniBtn danger" onclick="this.closest(\'.deductRow\').remove();calcLive()">控除削除</button></div></div>';$('areaDeductions').appendChild(div);calcLive()}
function clearDeductions(){$('areaDeductions').innerHTML='';calcLive()}
function collectDeductions(){return [...$('areaDeductions').querySelectorAll('.deductRow')].map(r=>{const h=Number(r.querySelector('.dedH').value)||0,w=Number(r.querySelector('.dedW').value)||0,q=Number(r.querySelector('.dedQ').value)||0;return{name:r.querySelector('.dedName').value,h,w,q,total:h*w*q}})}
function calcLive(){const item=itemById($('measureItem').value);if(!item){$('liveQty').textContent='0.00';$('liveUnit').textContent='';$('liveFormula').textContent='';return{qty:0,formula:'',deductions:[],input:{}}}let qty=0,formula='',deductions=[],input={};if(item.unit==='㎡'){const mode=$('areaMode').value;deductions=collectDeductions();const ded=deductions.reduce((a,b)=>a+b.total,0);if(mode==='flat'){const h=Number($('areaH').value)||0,w=Number($('areaW').value)||0,q=Number($('areaQ').value)||0;qty=Math.max(0,h*w*q-ded);formula=`${h} × ${w} × ${q} − 控除 ${ded.toFixed(2)} = ${qty.toFixed(2)}㎡`;input={mode,h,w,q,deductions}}else{const l=Number($('areaL').value)||0,hh=Number($('areaHeight').value)||0,d=Number($('areaDepth').value)||0,q=Number($('areaSame3d').value)||0;let base=0;if(mode==='face')base=l*hh;if(mode==='floor')base=l*d;if(mode==='around')base=(l+d)*2*hh;qty=Math.max(0,base*q-ded);const label=mode==='face'?`${l} × ${hh}`:mode==='floor'?`${l} × ${d}`:`(${l}＋${d})×2×${hh}`;formula=`${label} × ${q} − 控除 ${ded.toFixed(2)} = ${qty.toFixed(2)}㎡`;input={mode,l,hh,d,q,deductions}}}else if(item.unit==='m'){const l=Number($('lenL').value)||0,q=Number($('lenQ').value)||0,d=Number($('lenD').value)||0;qty=Math.max(0,l*q-d);formula=`${l} × ${q} − ${d} = ${qty.toFixed(2)}m`;input={l,q,d,lenDeductMemo:$('lenDeductMemo').value.trim()}}else{qty=Math.max(0,Number($('qtyValue').value)||0);formula=`数量 ${qty} ${item.unit}`;input={qty}}$('liveQty').textContent=fmt(qty,item.unit);$('liveUnit').textContent=item.unit;$('liveFormula').textContent=formula;return{qty,formula,deductions,input}}
document.addEventListener('input',e=>{if(['areaH','areaW','areaL','areaHeight','areaDepth','lenL','lenD','qtyValue','lenDeductMemo'].includes(e.target.id))calcLive()});
document.addEventListener('change',e=>{if(['areaQ','areaSame3d','lenQ','areaMode'].includes(e.target.id))calcLive()});
async function compressImage(file,max=1600,quality=.76){return new Promise(resolve=>{const img=new Image();const reader=new FileReader();reader.onload=e=>{img.onload=()=>{let w=img.width,h=img.height;if(Math.max(w,h)>max){if(w>h){h=Math.round(h*max/w);w=max}else{w=Math.round(w*max/h);h=max}}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.onerror=()=>resolve(null);img.src=e.target.result};reader.onerror=()=>resolve(null);reader.readAsDataURL(file)})}
async function previewEntryPhotos(input){for(const file of [...input.files]){const data=await compressImage(file);if(data)entryPhotoData.push(data)}input.value='';renderPhotoPreview()}
function renderPhotoPreview(){const box=$('entryPhotoPreview');box.innerHTML='';entryPhotoData.forEach((src,i)=>{const d=document.createElement('div');d.className='thumb';d.innerHTML='<img src="'+src+'"><button onclick="entryPhotoData.splice('+i+',1);renderPhotoPreview()">×</button>';box.appendChild(d)})}
function clearMeasureInputs(keepItem=true){edit={type:null,id:null};$('entrySubmit').textContent='登録';$('areaMode').value='flat';$('areaH').value='';$('areaW').value='';$('areaQ').value='1';$('areaL').value='';$('areaHeight').value='';$('areaDepth').value='';$('areaSame3d').value='1';$('lenL').value='';$('lenQ').value='1';$('lenD').value='';$('lenDeductMemo').value='';$('qtyValue').value='1';$('entryMemo').value='';clearDeductions();entryPhotoData=[];renderPhotoPreview();if(!keepItem)$('measureItem').selectedIndex=0;onMeasureItemChange()}
function submitEntry(continueSame){return edit.type==='entry'?updateEntry():saveEntry(continueSame)}
function saveEntry(continueSame){const s=currentSite();const item=itemById($('measureItem').value);if(!s){alert('先に現場を選択してください');return}if(!item){alert('項目を選択してください');return}const c=calcLive();if(c.qty<=0&&!confirm('数量が0です。登録しますか？'))return;const now=new Date().toISOString();s.entries.unshift({id:uid(),itemId:item.id,itemName:item.name,unit:item.unit,qty:c.qty,formula:c.formula,input:c.input,deductions:c.deductions||[],memo:$('entryMemo').value.trim(),photos:[...entryPhotoData],createdAt:now,updatedAt:now});s.updatedAt=now;if(!safeSave())return;clearMeasureInputs(true);renderAll();if(!continueSame)showView('result')}
function startEditEntry(id){const s=currentSite();const e=s?.entries.find(x=>x.id===id);if(!e)return;edit={type:'entry',id};$('measureItem').value=e.itemId;onMeasureItemChange();const inp=e.input||{};if(e.unit==='㎡'){$('areaMode').value=inp.mode||'flat';onAreaModeChange();if((inp.mode||'flat')==='flat'){$('areaH').value=inp.h??'';$('areaW').value=inp.w??'';$('areaQ').value=inp.q??1}else{$('areaL').value=inp.l??'';$('areaHeight').value=inp.hh??'';$('areaDepth').value=inp.d??'';$('areaSame3d').value=inp.q??1}clearDeductions();(inp.deductions||e.deductions||[]).forEach(d=>addDeduction('㎡',d))}else if(e.unit==='m'){$('lenL').value=inp.l??'';$('lenQ').value=inp.q??1;$('lenD').value=inp.d??'';$('lenDeductMemo').value=inp.lenDeductMemo||''}else{$('qtyValue').value=inp.qty??e.qty}$('entryMemo').value=e.memo||'';entryPhotoData=[...(e.photos||[])];renderPhotoPreview();$('entrySubmit').textContent='実測を更新';showView('measure');setTimeout(()=>$('measureForm').scrollIntoView({block:'start'}),50);calcLive()}
function updateEntry(){const s=currentSite();const e=s?.entries.find(x=>x.id===edit.id);const item=itemById($('measureItem').value);if(!s||!e||!item)return;const c=calcLive();Object.assign(e,{itemId:item.id,itemName:item.name,unit:item.unit,qty:c.qty,formula:c.formula,input:c.input,deductions:c.deductions||[],memo:$('entryMemo').value.trim(),photos:[...entryPhotoData],updatedAt:new Date().toISOString()});s.updatedAt=e.updatedAt;if(!safeSave())return;clearMeasureInputs(true);renderAll();showView('result')}
function deleteEntry(id){const s=currentSite();if(!s)return;if(confirm('この実測を削除しますか？')){s.entries=s.entries.filter(e=>e.id!==id);safeSave();renderAll()}}
function toggleHistory(){historyCollapsed=!historyCollapsed;renderMeasure()}
function totals(site){const map={};(site?.items||[]).forEach(i=>map[i.id]={item:i,total:0,count:0,photos:0});(site?.entries||[]).forEach(e=>{if(!map[e.itemId])map[e.itemId]={item:{id:e.itemId,name:e.itemName,unit:e.unit},total:0,count:0,photos:0};map[e.itemId].total+=Number(e.qty)||0;map[e.itemId].count++;map[e.itemId].photos+=(e.photos||[]).length});return Object.values(map).filter(x=>x.count>0||x.item)}
function renderSites(){const box=$('siteList');box.innerHTML='';const q=($('siteSearch')?.value||'').trim().toLowerCase();const sites=db.sites.filter(s=>(s.name+s.address+s.memo).toLowerCase().includes(q));if(!sites.length){box.innerHTML='<div class="empty">登録現場がありません</div>';return}sites.forEach(s=>{const d=document.createElement('div');d.className='siteCard '+(s.id===db.currentId?'active':'');d.innerHTML='<div class="cardHead"><div><div class="title">'+escapeHtml(s.name)+'</div><div class="meta">'+(s.date||'日付なし')+' / 項目 '+(s.items||[]).length+' / 実測 '+(s.entries||[]).length+'</div><div class="meta">'+escapeHtml(s.address||'')+'</div></div><span class="badge">'+(s.id===db.currentId?'選択中':'現場')+'</span></div><div class="btnRow noPrint" style="margin-top:10px"><button class="miniBtn primary" onclick="selectSite(\''+s.id+'\');showView(\'measure\')">この現場で実測</button><button class="miniBtn blue" onclick="selectSite(\''+s.id+'\');showView(\'result\')">結果</button><button class="miniBtn" onclick="startEditSite(\''+s.id+'\')">編集</button><button class="miniBtn" onclick="duplicateSite(\''+s.id+'\')">複製</button><button class="miniBtn danger" onclick="deleteSite(\''+s.id+'\')">現場ごと削除</button></div>';box.appendChild(d)})}
function renderItems(){const s=currentSite();$('noSiteItems').classList.toggle('hidden',!!s);$('itemForm').classList.toggle('hidden',!s);updateGroupFilter();const box=$('itemList');box.innerHTML='';if(!s){box.innerHTML='<div class="empty">現場未選択</div>';return}const items=filteredItems();if(!items.length){box.innerHTML='<div class="empty">項目がありません</div>';return}items.forEach(i=>{const d=document.createElement('div');d.className='itemCard';d.innerHTML='<div class="cardHead"><div><div class="title">'+escapeHtml(i.name)+' <span class="badge unit">'+i.unit+'</span></div><div class="meta">'+escapeHtml(i.group||'分類なし')+'</div><div class="small">'+escapeHtml(i.memo||'')+'</div></div><div class="btnRow noPrint"><button class="miniBtn" onclick="startEditItem(\''+i.id+'\')">編集</button><button class="miniBtn danger" onclick="deleteItem(\''+i.id+'\')">削除</button></div></div>';box.appendChild(d)})}
function renderMeasure(){const s=currentSite();$('noSiteMeasure').classList.toggle('hidden',!!s);$('measureForm').classList.toggle('hidden',!s);const sel=$('measureItem');const val=sel.value;sel.innerHTML='';if(s){filteredItems().forEach(i=>{const o=document.createElement('option');o.value=i.id;o.textContent=i.name+'（'+i.unit+'）';sel.appendChild(o)});if([...sel.options].some(o=>o.value===val))sel.value=val}onMeasureItemChange();const box=$('entryList');box.innerHTML='';if(!s||!s.entries.length){box.innerHTML='<div class="empty">実測データがありません</div>';return}if(historyCollapsed){box.innerHTML='<div class="empty">履歴を折りたたみ中：'+s.entries.length+'件</div>';return}s.entries.forEach(e=>box.appendChild(entryNode(e)))}
function entryNode(e){const d=document.createElement('div');d.className='entryCard';const photos=(e.photos||[]).slice(0,4).map(p=>'<div class="thumb"><img src="'+p+'"></div>').join('');d.innerHTML='<div class="cardHead"><div><div class="title">'+escapeHtml(e.itemName)+' <span class="badge unit">'+e.unit+'</span></div><div class="meta">'+new Date(e.createdAt).toLocaleString('ja-JP')+'</div></div><div class="total">'+fmt(e.qty,e.unit)+e.unit+'</div></div><div class="hint">'+escapeHtml(e.formula||'')+'</div>'+(e.memo?'<div class="small">メモ：'+escapeHtml(e.memo)+'</div>':'')+(photos?'<div class="photoGrid">'+photos+'</div>':'')+'<div class="btnRow noPrint" style="margin-top:8px"><button class="miniBtn" onclick="startEditEntry(\''+e.id+'\')">編集</button><button class="miniBtn danger" onclick="deleteEntry(\''+e.id+'\')">削除</button></div>';return d}
function renderResult(){const s=currentSite();const summary=$('resultSummary');summary.innerHTML='';if(!s){summary.innerHTML='<div class="empty">現場未選択</div>';$('resultList').innerHTML='';return}const t=totals(s);const photoCount=s.entries.reduce((a,e)=>a+(e.photos||[]).length,0);summary.innerHTML='<div class="summaryBox"><b>'+s.items.length+'</b><span>登録項目</span></div><div class="summaryBox"><b>'+s.entries.length+'</b><span>実測数</span></div><div class="summaryBox"><b>'+t.filter(x=>x.count>0).length+'</b><span>実測済項目</span></div><div class="summaryBox"><b>'+photoCount+'</b><span>写真</span></div>';const box=$('resultList');box.innerHTML='';if(!t.length){box.innerHTML='<div class="empty">集計対象がありません</div>';return}t.forEach(x=>{const entries=s.entries.filter(e=>e.itemId===x.item.id);const d=document.createElement('div');d.className='resultCard';d.innerHTML='<div class="cardHead"><div><div class="title">'+escapeHtml(x.item.name)+' <span class="badge unit">'+x.item.unit+'</span></div><div class="meta">実測 '+x.count+' 件 / 写真 '+x.photos+' 枚</div></div><div class="total">'+fmt(x.total,x.item.unit)+x.item.unit+'</div></div><div class="list" style="margin-top:10px">'+entries.map(e=>'<div class="small">・'+fmt(e.qty,e.unit)+e.unit+'｜'+escapeHtml(e.formula||'')+(e.memo?'｜'+escapeHtml(e.memo):'')+'</div>').join('')+'</div>';box.appendChild(d)})}
function resultText(){const s=currentSite();if(!s)return'';let lines=['【現調結果】',`現場名：${s.name}`,`現調日：${s.date||''}`,`担当者：${s.staff||''}`,`住所：${s.address||''}`,''];totals(s).forEach(x=>{if(x.count>0)lines.push(`${x.item.name}\t${fmt(x.total,x.item.unit)}${x.item.unit}\t実測${x.count}件`)});lines.push('',`現場メモ：${s.memo||''}`);return lines.join('\n')}
async function copyResultText(){const text=resultText();if(!text){alert('現場を選択してください');return}try{await navigator.clipboard.writeText(text);alert('現調結果をコピーしました')}catch(e){alert(text)}}
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportCsv(){const s=currentSite();if(!s){alert('現場を選択してください');return}let rows=[['現場名','項目名','単位','合計数量','実測件数','写真枚数','計算式・メモ']];totals(s).forEach(x=>{if(x.count>0){const entries=s.entries.filter(e=>e.itemId===x.item.id).map(e=>(e.formula||'')+(e.memo?' / '+e.memo:'')).join(' | ');rows.push([s.name,x.item.name,x.item.unit,fmt(x.total,x.item.unit),x.count,x.photos,entries])}});download('\ufeff'+rows.map(r=>r.map(csvEscape).join(',')).join('\n'),fileName('.csv'),'text/csv;charset=utf-8')}
function fileName(ext){const s=currentSite();return '現調台帳_'+(s?.name||'全現場')+'_'+today()+ext}
function download(text,name,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCurrentSiteJson(){const s=currentSite();if(!s){alert('現場を選択してください');return}download(JSON.stringify({type:'site',site:s},null,2),fileName('.json'),'application/json;charset=utf-8')}
function exportAllJson(){download(JSON.stringify({type:'all',db},null,2),'現調台帳_全現場_'+today()+'.json','application/json;charset=utf-8')}
function importJsonClick(){$('jsonIn').click()}
function importJson(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{try{const data=JSON.parse(e.target.result);if(data.type==='all'&&data.db?.sites){if(confirm('全現場データを現在のデータに追加しますか？「キャンセル」で置き換えます。')){db.sites=[...data.db.sites.map(s=>cloneSiteWithNewIds(s,true)),...db.sites]}else{db={sites:data.db.sites.map(s=>cloneSiteWithNewIds(s,true)),currentId:null};db.currentId=db.sites[0]?.id||null}}else if(data.type==='site'&&data.site){const ns=cloneSiteWithNewIds(data.site,true);db.sites.unshift(ns);db.currentId=ns.id}else if(Array.isArray(data.sites)){db={sites:data.sites.map(s=>cloneSiteWithNewIds(s,true)),currentId:null};db.currentId=db.sites[0]?.id||null}else{alert('対応していないJSONです');return}if(!safeSave())return;renderAll();alert('復元しました。IDは自動で振り直しています。')}catch(err){alert('JSONを読めませんでした')}};r.readAsText(f);input.value=''}
function defaultTemplates(){return[{name:'外壁',unit:'㎡',group:'外壁',memo:'縦×横、開口控除'},{name:'軒天',unit:'㎡',group:'外壁',memo:'縦×横'},{name:'屋根',unit:'㎡',group:'屋根',memo:'長さ×奥行き等'},{name:'四周壁',unit:'㎡',group:'外壁',memo:'（長さ＋奥行き）×2×高さ'},{name:'シーリング',unit:'m',group:'シーリング',memo:'長さ×同寸法、控除'},{name:'鉄部',unit:'㎡',group:'鉄部',memo:'面積拾い'},{name:'鉄部小物',unit:'箇所',group:'鉄部',memo:'箇所数'},{name:'雨樋',unit:'m',group:'付帯',memo:'延長'},{name:'養生',unit:'式',group:'共通',memo:'現場条件により一式'}]}
function addDefaultTemplates(){const s=currentSite();if(!s){alert('先に現場を選択してください');return}let added=0;defaultTemplates().forEach(t=>{if(!s.items.some(i=>i.name===t.name&&i.unit===t.unit)){s.items.push({...t,id:uid(),createdAt:new Date().toISOString()});added++}});if(!safeSave())return;renderAll();alert(added+'件追加しました')}
function saveCurrentItemsAsTemplate(){const s=currentSite();if(!s){alert('現場を選択してください');return}const name=prompt('テンプレート名','現場項目テンプレート');if(!name)return;const list=JSON.parse(localStorage.getItem(TPL_STORE)||'[]');list.unshift({id:uid(),name,items:s.items.map(({name,unit,group,memo})=>({name,unit,group,memo})),createdAt:new Date().toISOString()});localStorage.setItem(TPL_STORE,JSON.stringify(list));renderTemplates();alert('保存しました')}
function applySavedTemplate(){const s=currentSite();if(!s){alert('現場を選択してください');return}const list=JSON.parse(localStorage.getItem(TPL_STORE)||'[]');if(!list.length){alert('保存テンプレートがありません');return}const msg=list.map((t,i)=>`${i+1}: ${t.name}`).join('\n');const n=Number(prompt('適用する番号を入力\n'+msg,'1'))-1;const tpl=list[n];if(!tpl)return;let added=0;tpl.items.forEach(t=>{if(!s.items.some(i=>i.name===t.name&&i.unit===t.unit)){s.items.push({...t,id:uid(),createdAt:new Date().toISOString()});added++}});if(!safeSave())return;renderAll();alert(added+'件追加しました')}
function renderTemplates(){const box=$('templateList');if(!box)return;const list=JSON.parse(localStorage.getItem(TPL_STORE)||'[]');box.innerHTML=list.length?list.map(t=>'<div class="templateCard"><div class="title">'+escapeHtml(t.name)+'</div><div class="meta">項目 '+t.items.length+' 件</div></div>').join(''):'<div class="empty">保存テンプレートなし</div>'}
function renderAll(){const s=currentSite();$('currentSitePill').textContent=s?s.name:'現場未選択';renderFooter();renderSites();renderItems();renderMeasure();renderResult();renderTemplates()}
load();
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
