function mobileGlobalItems(){try{return typeof activeSetItems==='function'?activeSetItems():(typeof favoriteGlobalItems==='function'?favoriteGlobalItems():[])}catch(e){return[]}}
function currentMeasureValue(){return document.getElementById('measureItem')?.value||''}
function setMeasureValue(id){const sel=document.getElementById('measureItem');if(!sel)return;if([...sel.options].some(o=>o.value===id)){sel.value=id;onMeasureItemChange();highlightQuick(id);focusFirstMeasureField()}}
function highlightQuick(id){document.querySelectorAll('.quickItemBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===id))}
function focusFirstMeasureField(){setTimeout(()=>{const ids=['areaH','areaL','lenL','qtyValue'];for(const id of ids){const el=document.getElementById(id);if(el&&!el.closest('.hidden')){el.focus();break}}},80)}
function setLaserMode(mode){const m=document.getElementById('areaMode');if(!m)return;m.value=mode;onAreaModeChange();calcLive();document.querySelectorAll('.laserModeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));focusFirstMeasureField()}
function openCamera(){const input=document.getElementById('entryPhotos');if(input)input.click()}
function renderMobileQuickPanel(){const form=document.getElementById('measureForm');if(!form)return;let panel=document.getElementById('mobileQuickPanel');if(!panel){panel=document.createElement('div');panel.id='mobileQuickPanel';panel.className='mobileQuickPanel noPrint';form.insertBefore(panel,form.firstChild)}const items=mobileGlobalItems();const selected=currentMeasureValue();panel.innerHTML='<div class="quickTitle">セット項目ワンタップ</div><div class="quickButtons">'+(items.length?items.map(i=>'<button class="quickItemBtn '+(i.id===selected?'active':'')+'" data-id="'+i.id+'" onclick="setMeasureValue(\''+i.id+'\')">'+escapeHtml(i.name)+'<br><span class="small">'+i.unit+'</span></button>').join(''):'<span class="small">保管画面で項目セットを選択してください</span>')+'</div><div class="laserButtons"><button class="laserModeBtn" data-mode="face" onclick="setLaserMode(\'face\')">長さ×高さ</button><button class="laserModeBtn" data-mode="floor" onclick="setLaserMode(\'floor\')">長さ×奥行き</button><button class="laserModeBtn" data-mode="around" onclick="setLaserMode(\'around\')">四周計算</button></div><button class="photoAction" onclick="openCamera()">写真を撮る / 追加</button><div class="oneHandHint">片手操作用：項目選択 → 写真 → 数量入力 → 続けて登録</div>'}
function renderPhotoListPanel(){const result=document.getElementById('view-result');if(!result)return;let panel=document.getElementById('photoListPanel');if(!panel){panel=document.createElement('div');panel.id='photoListPanel';panel.className='card flat';result.appendChild(panel)}const s=currentSite();if(!s){panel.innerHTML='<h2><span class="num">3</span>写真一覧</h2><div class="empty">現場未選択</div>';return}const photos=[];(s.entries||[]).forEach(e=>(e.photos||[]).forEach((p,idx)=>photos.push({src:p,item:e.itemName,qty:e.qty,unit:e.unit,idx})));panel.innerHTML='<h2><span class="num">3</span>写真一覧</h2>'+(photos.length?'<div class="photoListGrid">'+photos.map(p=>'<div class="photoCard"><img src="'+p.src+'"><div>'+escapeHtml(p.item)+' / '+fmt(p.qty,p.unit)+p.unit+'</div></div>').join('')+'</div>':'<div class="empty">写真がありません</div>')}
const mobileBaseRenderAll=window.renderAll;
window.renderAll=function(){mobileBaseRenderAll();renderMobileQuickPanel();renderPhotoListPanel()};
const mobileBaseOnMeasureItemChange=window.onMeasureItemChange;
window.onMeasureItemChange=function(){const r=mobileBaseOnMeasureItemChange();highlightQuick(currentMeasureValue());const m=document.getElementById('areaMode');if(m)document.querySelectorAll('.laserModeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m.value));return r};
setTimeout(()=>{renderMobileQuickPanel();renderPhotoListPanel()},0);
